package com.example.pethospitalmanagement.entity;

import java.math.BigDecimal;

public class Drug {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drug.drugId
     *
     * @mbggenerated
     */
    private Integer drugid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drug.drugName
     *
     * @mbggenerated
     */
    private String drugname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drug.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drug.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drug.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drug.sl
     *
     * @mbggenerated
     */
    private Long sl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_drug.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drug.drugId
     *
     * @return the value of t_drug.drugId
     *
     * @mbggenerated
     */
    public Integer getDrugid() {
        return drugid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drug.drugId
     *
     * @param drugid the value for t_drug.drugId
     *
     * @mbggenerated
     */
    public void setDrugid(Integer drugid) {
        this.drugid = drugid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drug.drugName
     *
     * @return the value of t_drug.drugName
     *
     * @mbggenerated
     */
    public String getDrugname() {
        return drugname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drug.drugName
     *
     * @param drugname the value for t_drug.drugName
     *
     * @mbggenerated
     */
    public void setDrugname(String drugname) {
        this.drugname = drugname == null ? null : drugname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drug.unit
     *
     * @return the value of t_drug.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drug.unit
     *
     * @param unit the value for t_drug.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drug.description
     *
     * @return the value of t_drug.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drug.description
     *
     * @param description the value for t_drug.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drug.price
     *
     * @return the value of t_drug.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drug.price
     *
     * @param price the value for t_drug.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drug.sl
     *
     * @return the value of t_drug.sl
     *
     * @mbggenerated
     */
    public Long getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drug.sl
     *
     * @param sl the value for t_drug.sl
     *
     * @mbggenerated
     */
    public void setSl(Long sl) {
        this.sl = sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_drug.money
     *
     * @return the value of t_drug.money
     *
     * @mbggenerated
     */
    public BigDecimal getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_drug.money
     *
     * @param money the value for t_drug.money
     *
     * @mbggenerated
     */
    public void setMoney(BigDecimal money) {
        this.money = money;
    }
}