package com.example.pethospitalmanagement.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class FosterCare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fostercare.fosterId
     *
     * @mbggenerated
     */
    private String fosterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fostercare.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fostercare.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fostercare.petName
     *
     * @mbggenerated
     */
    private String petname;

    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fostercare.startTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fostercare.endTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date endtime;

    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_fostercare.details
     *
     * @mbggenerated
     */
    private String details;

    private String state;

    private String evaluation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fostercare.fosterId
     *
     * @return the value of t_fostercare.fosterId
     *
     * @mbggenerated
     */
    public String getFosterid() {
        return fosterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fostercare.fosterId
     *
     * @param fosterid the value for t_fostercare.fosterId
     *
     * @mbggenerated
     */
    public void setFosterid(String fosterid) {
        this.fosterid = fosterid == null ? null : fosterid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fostercare.userId
     *
     * @return the value of t_fostercare.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fostercare.userId
     *
     * @param userid the value for t_fostercare.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fostercare.userName
     *
     * @return the value of t_fostercare.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fostercare.userName
     *
     * @param username the value for t_fostercare.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fostercare.petName
     *
     * @return the value of t_fostercare.petName
     *
     * @mbggenerated
     */
    public String getPetname() {
        return petname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fostercare.petName
     *
     * @param petname the value for t_fostercare.petName
     *
     * @mbggenerated
     */
    public void setPetname(String petname) {
        this.petname = petname == null ? null : petname.trim();
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fostercare.startTime
     *
     * @return the value of t_fostercare.startTime
     *
     * @mbggenerated
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fostercare.startTime
     *
     * @param starttime the value for t_fostercare.startTime
     *
     * @mbggenerated
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fostercare.endTime
     *
     * @return the value of t_fostercare.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fostercare.endTime
     *
     * @param endtime the value for t_fostercare.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_fostercare.details
     *
     * @return the value of t_fostercare.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_fostercare.details
     *
     * @param details the value for t_fostercare.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getEvaluation() {
        return evaluation;
    }

    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation;
    }
}