package com.example.pethospitalmanagement.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class Log {

    private Integer id;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.logId
     *
     * @mbggenerated
     */
    private String logid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.method
     *
     * @mbggenerated
     */
    private String method;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.logType
     *
     * @mbggenerated
     */
    private String logtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.requestIp
     *
     * @mbggenerated
     */
    private String requestip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.exceptionCode
     *
     * @mbggenerated
     */
    private String exceptioncode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.exceptionDetail
     *
     * @mbggenerated
     */
    private String exceptiondetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.createBy
     *
     * @mbggenerated
     */
    private String createby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_log.createDate
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd HH:mm:ss")
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
    private Date createdate;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.logId
     *
     * @return the value of t_log.logId
     *
     * @mbggenerated
     */
    public String getLogid() {
        return logid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.logId
     *
     * @param logid the value for t_log.logId
     *
     * @mbggenerated
     */
    public void setLogid(String logid) {
        this.logid = logid == null ? null : logid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.description
     *
     * @return the value of t_log.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.description
     *
     * @param description the value for t_log.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.method
     *
     * @return the value of t_log.method
     *
     * @mbggenerated
     */
    public String getMethod() {
        return method;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.method
     *
     * @param method the value for t_log.method
     *
     * @mbggenerated
     */
    public void setMethod(String method) {
        this.method = method == null ? null : method.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.logType
     *
     * @return the value of t_log.logType
     *
     * @mbggenerated
     */
    public String getLogtype() {
        return logtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.logType
     *
     * @param logtype the value for t_log.logType
     *
     * @mbggenerated
     */
    public void setLogtype(String logtype) {
        this.logtype = logtype == null ? null : logtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.requestIp
     *
     * @return the value of t_log.requestIp
     *
     * @mbggenerated
     */
    public String getRequestip() {
        return requestip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.requestIp
     *
     * @param requestip the value for t_log.requestIp
     *
     * @mbggenerated
     */
    public void setRequestip(String requestip) {
        this.requestip = requestip == null ? null : requestip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.exceptionCode
     *
     * @return the value of t_log.exceptionCode
     *
     * @mbggenerated
     */
    public String getExceptioncode() {
        return exceptioncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.exceptionCode
     *
     * @param exceptioncode the value for t_log.exceptionCode
     *
     * @mbggenerated
     */
    public void setExceptioncode(String exceptioncode) {
        this.exceptioncode = exceptioncode == null ? null : exceptioncode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.exceptionDetail
     *
     * @return the value of t_log.exceptionDetail
     *
     * @mbggenerated
     */
    public String getExceptiondetail() {
        return exceptiondetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.exceptionDetail
     *
     * @param exceptiondetail the value for t_log.exceptionDetail
     *
     * @mbggenerated
     */
    public void setExceptiondetail(String exceptiondetail) {
        this.exceptiondetail = exceptiondetail == null ? null : exceptiondetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.createBy
     *
     * @return the value of t_log.createBy
     *
     * @mbggenerated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.createBy
     *
     * @param createby the value for t_log.createBy
     *
     * @mbggenerated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_log.createDate
     *
     * @return the value of t_log.createDate
     *
     * @mbggenerated
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_log.createDate
     *
     * @param createdate the value for t_log.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}