package com.example.pethospitalmanagement.entity;

public class Pet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.breed
     *
     * @mbggenerated
     */
    private String breed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pet.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.id
     *
     * @return the value of t_pet.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.id
     *
     * @param id the value for t_pet.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.name
     *
     * @return the value of t_pet.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.name
     *
     * @param name the value for t_pet.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.type
     *
     * @return the value of t_pet.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.type
     *
     * @param type the value for t_pet.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.breed
     *
     * @return the value of t_pet.breed
     *
     * @mbggenerated
     */
    public String getBreed() {
        return breed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.breed
     *
     * @param breed the value for t_pet.breed
     *
     * @mbggenerated
     */
    public void setBreed(String breed) {
        this.breed = breed == null ? null : breed.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.description
     *
     * @return the value of t_pet.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.description
     *
     * @param  description the value for t_pet.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pet.note
     *
     * @return the value of t_pet.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pet.note
     *
     * @param note the value for t_pet.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}