package com.example.pethospitalmanagement.entity;

import com.fasterxml.jackson.annotation.JsonFormat;
import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class SeeDoctor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.seeDoctorId
     *
     * @mbggenerated
     */
    private String seedoctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.doctorId
     *
     * @mbggenerated
     */
    private Integer doctorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.doctorName
     *
     * @mbggenerated
     */
    private String doctorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.userName
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.petName
     *
     * @mbggenerated
     */
    private String petname;

    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.doctorTime
     *
     * @mbggenerated
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date doctortime;

    @DateTimeFormat(pattern="yyyy-MM-dd")
    @JsonFormat(pattern="yyyy-MM-dd",timezone="GMT+8")
    private Date createtime;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.details
     *
     * @mbggenerated
     */
    private String details;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_seedoctor.evaluation
     *
     * @mbggenerated
     */
    private String evaluation;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.seeDoctorId
     *
     * @return the value of t_seedoctor.seeDoctorId
     *
     * @mbggenerated
     */
    public String getSeedoctorid() {
        return seedoctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.seeDoctorId
     *
     * @param seedoctorid the value for t_seedoctor.seeDoctorId
     *
     * @mbggenerated
     */
    public void setSeedoctorid(String seedoctorid) {
        this.seedoctorid = seedoctorid == null ? null : seedoctorid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.doctorId
     *
     * @return the value of t_seedoctor.doctorId
     *
     * @mbggenerated
     */
    public Integer getDoctorid() {
        return doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.doctorId
     *
     * @param doctorid the value for t_seedoctor.doctorId
     *
     * @mbggenerated
     */
    public void setDoctorid(Integer doctorid) {
        this.doctorid = doctorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.doctorName
     *
     * @return the value of t_seedoctor.doctorName
     *
     * @mbggenerated
     */
    public String getDoctorname() {
        return doctorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.doctorName
     *
     * @param doctorname the value for t_seedoctor.doctorName
     *
     * @mbggenerated
     */
    public void setDoctorname(String doctorname) {
        this.doctorname = doctorname == null ? null : doctorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.userId
     *
     * @return the value of t_seedoctor.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.userId
     *
     * @param userid the value for t_seedoctor.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.userName
     *
     * @return the value of t_seedoctor.userName
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.userName
     *
     * @param username the value for t_seedoctor.userName
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.petName
     *
     * @return the value of t_seedoctor.petName
     *
     * @mbggenerated
     */
    public String getPetname() {
        return petname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.petName
     *
     * @param petname the value for t_seedoctor.petName
     *
     * @mbggenerated
     */
    public void setPetname(String petname) {
        this.petname = petname == null ? null : petname.trim();
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.doctorTime
     *
     * @return the value of t_seedoctor.doctorTime
     *
     * @mbggenerated
     */
    public Date getDoctortime() {
        return doctortime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.doctorTime
     *
     * @param doctortime the value for t_seedoctor.doctorTime
     *
     * @mbggenerated
     */
    public void setDoctortime(Date doctortime) {
        this.doctortime = doctortime;
    }

    public Date getCreatetime() {
        return createtime;
    }

    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.details
     *
     * @return the value of t_seedoctor.details
     *
     * @mbggenerated
     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.details
     *
     * @param details the value for t_seedoctor.details
     *
     * @mbggenerated
     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.state
     *
     * @return the value of t_seedoctor.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.state
     *
     * @param state the value for t_seedoctor.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_seedoctor.evaluation
     *
     * @return the value of t_seedoctor.evaluation
     *
     * @mbggenerated
     */
    public String getEvaluation() {
        return evaluation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_seedoctor.evaluation
     *
     * @param evaluation the value for t_seedoctor.evaluation
     *
     * @mbggenerated
     */
    public void setEvaluation(String evaluation) {
        this.evaluation = evaluation == null ? null : evaluation.trim();
    }
}