server:
  servlet:
    context-path: /pethospitalmanagement
  port: 8080

spring:
  datasource:
    name: pethospital
    url: jdbc:mysql://127.0.0.1:3306/pethospital?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  mail:
    host: smtp.163.com
    username: 18737661338@163.com
    password: peng18737661338
    default-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.example.pethospialmanagement.entity  # 注意：对应实体类的路径
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql