package com.example.pethospitalmanagement.mapper;

import com.example.pethospitalmanagement.entity.Drug;

import java.util.List;

public interface DrugMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drug
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer drugid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drug
     *
     * @mbggenerated
     */
    int insert(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drug
     *
     * @mbggenerated
     */
    int insertSelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drug
     *
     * @mbggenerated
     */
    Drug selectByPrimaryKey(Integer drugid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drug
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Drug record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_drug
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Drug record);

    List<Drug> selectAllDrugByPrimaryKeySelective(Drug Drug);
}