package com.example.pethospitalmanagement.mapper;

import com.example.pethospitalmanagement.entity.FosterCare;
import com.example.pethospitalmanagement.vo.FosterCareVo;

import java.util.List;

public interface FosterCareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fostercare
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String fosterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fostercare
     *
     * @mbggenerated
     */
    int insert(FosterCare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fostercare
     *
     * @mbggenerated
     */
    int insertSelective(FosterCare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fostercare
     *
     * @mbggenerated
     */
    FosterCare selectByPrimaryKey(String fosterid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fostercare
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FosterCare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_fostercare
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FosterCare record);

    int updateFosterCareEvaluation(FosterCare fosterCare);

    List<FosterCare> selectAllFosterCareByPrimaryKeySelective(FosterCareVo fosterCareVo);
}