package com.example.pethospitalmanagement.mapper;

import com.example.pethospitalmanagement.entity.Pet;

import java.util.List;

public interface PetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated
     */
    int insert(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated
     */
    int insertSelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated
     */
    Pet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pet
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Pet record);

    List<Pet> selectAllPetByPrimaryKey(Pet record);
}